In [4]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [5]:
# Yes there is
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [6]:
# printing data type of every element in list_
for i in list_:
    print(type(i))

# printing data type of every element in array_list
for a in array_list:
    print(type(a))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:

## array_list = np.array(object = list_, dtype = int)

## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and array_list

In [7]:
array_list = np.array(object = list_, dtype = int)
for a in array_list:
    print(type(a))
    
# Yes there is the difference

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [10]:
# Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
print(num_array)

[[1 2 3]
 [4 5 6]]


## Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [9]:
print(np.shape(num_array))
print(np.size(num_array))

(2, 3)
6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [16]:
numpy_array = np.zeros((3,3))
print(numpy_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


   ## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [18]:
mat = np.eye(5)
print(mat)
print(np.shape(mat))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
